### ISSUE TITLE
In rare cases players are not sent from lobby to map when the game starts

### ISSUE THREAD

**Issue by imfi-jz** [imfi-jz/SOPROJ11Q-Mobile#26]
Huidig resultaat: je scherm blijft in de lobby terwijl het spel eigenlijk start.
Verwacht resultaat: je scherm gaat van lobby naar kaart bij het starten van het spel.

Dit komt af en toe voor. Er moet wellicht validatie komen of alle spelers in het kaart scherm zijn voordat het spel kan beginnen. 

Ik verwacht dat dit komt doordat de socket connectie nog niet klaar is, of dat het signaal toevallig gemist wordt.

**Comment by lderkzen** [comment]
Dit gebeurd nog steeds
