### ISSUE TITLE
Leaving a lobby does not remove the client from the game

### ISSUE THREAD

**Issue by imfi-jz** [imfi-jz/SOPROJ11Q-Mobile#32]
Reproduceren: 
1. Voer een geldige code in.
2. Voer een naam in en betreed de lobby.
3. Verlaat de lobby.
4. Start het spel.

Huidig resultaat: de client navigeert naar de het speelscherm van de game die hij/zij verlaten had.
Gewenst resultaat: de client wordt niet meer meegenomen in het starten van het spel en blijft in het hoofdscherm.

**Comment by lderkzen** [comment]
Er is overigens nog helemaal niks wat betreft het opruimen van oude database entries (zoals users) dus dit is eigenlijk een nieuwe feature

**Comment by imfi-jz** [comment]
Spelers kunnen de lobby niet meer verlaten
