### ISSUE TITLE
Invite keys are not linked to user in database when joining a game

### ISSUE THREAD

**Issue by imfi-jz** [imfi-jz/SOPROJ11Q-Mobile#36]
Reproduce:
1. Voer code in
2. Voer naam in
3. (optioneel: start het spel)

Resultaat: de spelende gebruiker wordt in de client goed gelinkt aan zijn invite key, maar dit wordt niet naar de database verstuurd dus weten andere gebruikers niet dat de gebruiker in het spel zit.
Verwacht resultaat: alle gebruikers in het spel zijn in de database gelinkt aan hun invite key en kunnen worden opgehaald als mede speler in het spel met bijbehorende rol.

**Comment by Stupers** [comment]
Nagekeken, het verwachte resultaat is al actueel

**Comment by imfi-jz** [comment]
> Nagekeken, het verwachte resultaat is al actueel

Same for me
